/****************************************************
 *	BASE DE DATOS myspa                         *
 *                                                  *
 *	Archivo de Datos Base para pruebas (DML)    *
 ***************************************************/
 
 /*
    Version:        1.0
    Fecha:          17/04/2018 18:58:00
    Autor:          Miguel Angel Gil Rios
    Email:          angel.grios@gmail.com
    Comentarios:    Datos bÃ¡sicos para hacer pruebas
                    de consultas con la Base de Datos.
 */

USE myspa;

--  Datos personales [persona]:
--	Persona Virtual del Administrador:
INSERT INTO persona (idPersona, nombre, apellidoPaterno, apellidoMaterno, domicilio, telefono, rfc) VALUES(1, 'Administrador', '', '', '', '', 'ADMINISTRATOR');
--	
INSERT INTO persona (idPersona, nombre, apellidoPaterno, apellidoMaterno, genero, domicilio, telefono, rfc) VALUES(101, 'Fátima Paola', 'Alonso', 'Villalpando', 'F', 'Alhondiga # 316 Col. Heroes', '', 'AOVP851205');
INSERT INTO persona (idPersona, nombre, apellidoPaterno, apellidoMaterno, genero, domicilio, telefono, rfc) VALUES(102, 'Luis Carlos', 'Arredondo', 'Diaz', 'M', 'Mar Egeo #510 ', '', 'AEDL950402');
INSERT INTO persona (idPersona, nombre, apellidoPaterno, apellidoMaterno, genero, domicilio, telefono, rfc) VALUES(103, 'Juan Christopher', 'Bazaldúa', 'Ramírez', 'M', 'Blvd. Hidalgo 1150, Col. La Florida', '', 'BARJ961125');
INSERT INTO persona (idPersona, nombre, apellidoPaterno, apellidoMaterno, genero, domicilio, telefono, rfc) VALUES(104, 'Miguel Angel', 'Bernardino', 'Muñoz', 'M', 'Castaña 103, Col. Arboledas', '', 'BEMM880229');
INSERT INTO persona (idPersona, nombre, apellidoPaterno, apellidoMaterno, genero, domicilio, telefono, rfc) VALUES(105, 'Lisset Anahi', 'Conde', 'Aguiñaga', 'F', 'Blas Galindo #420, Col. Bosques', '', 'COAL980214');
INSERT INTO persona (idPersona, nombre, apellidoPaterno, apellidoMaterno, genero, domicilio, telefono, rfc) VALUES(106, 'Berenice ', 'Fernández', 'Vázquez', 'F', 'Rio Mayo #208, Col. Cerrito de Jerez', '', 'FEVB900816');
INSERT INTO persona (idPersona, nombre, apellidoPaterno, apellidoMaterno, genero, domicilio, telefono, rfc) VALUES(107, 'José Alejandro', 'Gutiérrez', 'Maldonado', 'M', 'Campeche 615, Col. Vistahermosa', '', 'GUMJ820315');
INSERT INTO persona (idPersona, nombre, apellidoPaterno, apellidoMaterno, genero, domicilio, telefono, rfc) VALUES(108, 'Adiel ', 'Hernández', 'Palacios', 'M', 'Guanajuato #131, Col. Peñitas', '', 'HEPA860923');
INSERT INTO persona (idPersona, nombre, apellidoPaterno, apellidoMaterno, genero, domicilio, telefono, rfc) VALUES(109, 'Elena Guadalupe', 'Jiménez', 'Solis', 'F', 'Paseo de los Insurgentes #1400, Col. Villa Insurgentes', '', 'JISE981223');
INSERT INTO persona (idPersona, nombre, apellidoPaterno, apellidoMaterno, genero, domicilio, telefono, rfc) VALUES(110, 'Luis Antonio', 'Quintero', 'Robledo', 'M', 'Baviera #321, Col. La Carmona', '', 'QURL900328');
INSERT INTO persona (idPersona, nombre, apellidoPaterno, apellidoMaterno, genero, domicilio, telefono, rfc) VALUES(111, 'José Alonso', 'Ramos', 'Rangel', 'M', 'Pio XI #123, Col. Valle de León', '', 'RARJ980603');
INSERT INTO persona (idPersona, nombre, apellidoPaterno, apellidoMaterno, genero, domicilio, telefono, rfc) VALUES(112, 'José María', 'Rios', 'Romo', 'M', 'Sultan #205, Col. Valle de Señora', '', 'RIRM980314');
INSERT INTO persona (idPersona, nombre, apellidoPaterno, apellidoMaterno, genero, domicilio, telefono, rfc) VALUES(113, 'Miguel Angel', 'Salas', 'Rangel', 'M', 'Paseo de los Gavilanes #233, Col. San Isidro', '', 'SARM800609');
INSERT INTO persona (idPersona, nombre, apellidoPaterno, apellidoMaterno, genero, domicilio, telefono, rfc) VALUES(114, 'Janeth Guadalupe', 'Salazar', 'Cabrera', 'F', 'Calle S/N', '', 'SACJ980413');
INSERT INTO persona (idPersona, nombre, apellidoPaterno, apellidoMaterno, genero, domicilio, telefono, rfc) VALUES(115, 'Javier ', 'Salazar', 'García', 'M', 'Prisma #121', '', 'SAGJ900719');
INSERT INTO persona (idPersona, nombre, apellidoPaterno, apellidoMaterno, genero, domicilio, telefono, rfc) VALUES(116, 'Marco Fabian', 'Sanchez', 'Perez', 'M', 'Santander #124, Col. San Juan Bosco', '', 'SAPM900606');
INSERT INTO persona (idPersona, nombre, apellidoPaterno, apellidoMaterno, genero, domicilio, telefono, rfc) VALUES(117, 'Blanca Erendira', 'Tejeda', 'Camacho', 'F', 'Inventores #614, Col. Aurora', '', 'TECB891117');
INSERT INTO persona (idPersona, nombre, apellidoPaterno, apellidoMaterno, genero, domicilio, telefono, rfc) VALUES(118, 'Jared Esteban', 'Alfaro', 'López', 'M', 'Uranio #222, Col. Echeveste', '', 'AALJ950906');
INSERT INTO persona (idPersona, nombre, apellidoPaterno, apellidoMaterno, genero, domicilio, telefono, rfc) VALUES(119, 'Roberto Damian', 'Cabrera', 'Alonso', 'M', 'Pedro Moreno 725, Col. Centro', '', 'CAAR901010');
INSERT INTO persona (idPersona, nombre, apellidoPaterno, apellidoMaterno, genero, domicilio, telefono, rfc) VALUES(120, 'Cristian Jesus', 'Estrada', 'Andrade', 'M', 'Bolivia 410, Col. Obrera', '', 'EAAC961216');
INSERT INTO persona (idPersona, nombre, apellidoPaterno, apellidoMaterno, genero, domicilio, telefono, rfc) VALUES(121, 'José María', 'Febronio', 'Manuel', 'M', 'Romita 310, Col. Industrial', '', 'FEMJ961231');
INSERT INTO persona (idPersona, nombre, apellidoPaterno, apellidoMaterno, genero, domicilio, telefono, rfc) VALUES(122, 'Saúl Moises', 'Hernández', 'García', 'M', 'Rio Panuco #215, Col. San Miguel', '', 'HEGS941216');
INSERT INTO persona (idPersona, nombre, apellidoPaterno, apellidoMaterno, genero, domicilio, telefono, rfc) VALUES(123, 'Mario Alberto', 'Hernández', 'Negrete', 'M', 'Pintores #123, Col. Echeveste', '', 'HENM980916');
INSERT INTO persona (idPersona, nombre, apellidoPaterno, apellidoMaterno, genero, domicilio, telefono, rfc) VALUES(124, 'Juan Arturo', 'López', 'Estrada', 'M', 'Horóscopo #125, Los Limones', '', 'LOEJ990516');
INSERT INTO persona (idPersona, nombre, apellidoPaterno, apellidoMaterno, genero, domicilio, telefono, rfc) VALUES(125, 'Diana Laura', 'López', 'Olivares', 'F', 'Honduras #423, Col. Industrial', '', 'LOOD980517');
INSERT INTO persona (idPersona, nombre, apellidoPaterno, apellidoMaterno, genero, domicilio, telefono, rfc) VALUES(126, 'Lizet Alejandra', 'Muñoz', 'Calderón', 'F', 'Yuriria 220, Col. Industrial', '', 'MUCL970917');
INSERT INTO persona (idPersona, nombre, apellidoPaterno, apellidoMaterno, genero, domicilio, telefono, rfc) VALUES(127, 'Manuela Noemí', 'Ornelas', 'Agripino', 'F', 'Materialistas # 610, Col. Echeveste', '', 'OEAM990315');
INSERT INTO persona (idPersona, nombre, apellidoPaterno, apellidoMaterno, genero, domicilio, telefono, rfc) VALUES(128, 'César Emmanuel', 'Pereira', 'Luna', 'M', 'Beethoven #126, Col. León Moderno', '', 'PELC941231');
INSERT INTO persona (idPersona, nombre, apellidoPaterno, apellidoMaterno, genero, domicilio, telefono, rfc) VALUES(129, 'Norma Liliana', 'Rico', 'Velázquez', 'F', 'Avenida Central #365, Col. Fraccionamiento Guadalupe', '', 'RIVN990814');
INSERT INTO persona (idPersona, nombre, apellidoPaterno, apellidoMaterno, genero, domicilio, telefono, rfc) VALUES(130, 'Victor Isaac', 'Robles', 'Gallo', 'M', 'Antillón #116, Col. Obrera', '', 'ROGV950607');
INSERT INTO persona (idPersona, nombre, apellidoPaterno, apellidoMaterno, genero, domicilio, telefono, rfc) VALUES(131, 'Diego Alejandro', 'Sabido', 'Valencia', 'M', 'Paseo de los Laureles #110, Col. Fraccionamiento Manatiales', '', 'SAVD920705');
INSERT INTO persona (idPersona, nombre, apellidoPaterno, apellidoMaterno, genero, domicilio, telefono, rfc) VALUES(132, 'Emmanuel ', 'Toledo', 'Castro', 'M', 'Calle S/N', '', 'TOCE950531');
INSERT INTO persona (idPersona, nombre, apellidoPaterno, apellidoMaterno, genero, domicilio, telefono, rfc) VALUES(133, 'Omar Ernesto', 'Trejo', 'Palafox', 'M', 'Aurora #301, Col. Valle de León', '', 'TEPO880617');



--	Usuarios [usuario]:
--	Usuario Administrador:
INSERT INTO usuario (idUsuario, nombreUsuario, contrasenia, rol) VALUES(1, 'admin', 'admin', 'Administrador');
--	
INSERT INTO usuario (idUsuario, nombreUsuario, contrasenia, rol) VALUES(101, 'aovp', 'u1234', 'Administrador');
INSERT INTO usuario (idUsuario, nombreUsuario, contrasenia, rol) VALUES(102, 'aedl', 'u1235', 'Administrador');
INSERT INTO usuario (idUsuario, nombreUsuario, contrasenia, rol) VALUES(103, 'barj', 'u1236', 'Administrador');
INSERT INTO usuario (idUsuario, nombreUsuario, contrasenia, rol) VALUES(104, 'bemm', 'u1237', 'Recepcionista');
INSERT INTO usuario (idUsuario, nombreUsuario, contrasenia, rol) VALUES(105, 'coal', 'u1238', 'Recepcionista');
INSERT INTO usuario (idUsuario, nombreUsuario, contrasenia, rol) VALUES(106, 'fevb', 'u1239', 'Recepcionista');
INSERT INTO usuario (idUsuario, nombreUsuario, contrasenia, rol) VALUES(107, 'gumj', 'u1240', 'Recepcionista');
INSERT INTO usuario (idUsuario, nombreUsuario, contrasenia, rol) VALUES(108, 'hepa', 'u1241', 'Tecnico');
INSERT INTO usuario (idUsuario, nombreUsuario, contrasenia, rol) VALUES(109, 'jise', 'u1242', 'Tecnico');
INSERT INTO usuario (idUsuario, nombreUsuario, contrasenia, rol) VALUES(110, 'qurl', 'u1243', 'Tecnico');
INSERT INTO usuario (idUsuario, nombreUsuario, contrasenia, rol) VALUES(111, 'rarj', 'u1244', 'Tecnico');
INSERT INTO usuario (idUsuario, nombreUsuario, contrasenia, rol) VALUES(112, 'rirm', 'u1245', 'Tecnico');
INSERT INTO usuario (idUsuario, nombreUsuario, contrasenia, rol) VALUES(113, 'sarm', 'u1246', 'Tecnico');
INSERT INTO usuario (idUsuario, nombreUsuario, contrasenia, rol) VALUES(114, 'sacj', 'u1247', 'Tecnico');
INSERT INTO usuario (idUsuario, nombreUsuario, contrasenia, rol) VALUES(115, 'sagj', 'u1248', 'Tecnico');
INSERT INTO usuario (idUsuario, nombreUsuario, contrasenia, rol) VALUES(116, 'sapm', 'u1249', 'Tecnico');
INSERT INTO usuario (idUsuario, nombreUsuario, contrasenia, rol) VALUES(117, 'tecb', 'u1250', 'Cliente');
INSERT INTO usuario (idUsuario, nombreUsuario, contrasenia, rol) VALUES(118, 'aalj', 'u1251', 'Cliente');
INSERT INTO usuario (idUsuario, nombreUsuario, contrasenia, rol) VALUES(119, 'caar', 'u1252', 'Cliente');
INSERT INTO usuario (idUsuario, nombreUsuario, contrasenia, rol) VALUES(120, 'eaac', 'u1253', 'Cliente');
INSERT INTO usuario (idUsuario, nombreUsuario, contrasenia, rol) VALUES(121, 'femj', 'u1254', 'Cliente');
INSERT INTO usuario (idUsuario, nombreUsuario, contrasenia, rol) VALUES(122, 'hegs', 'u1255', 'Cliente');
INSERT INTO usuario (idUsuario, nombreUsuario, contrasenia, rol) VALUES(123, 'henm', 'u1256', 'Cliente');
INSERT INTO usuario (idUsuario, nombreUsuario, contrasenia, rol) VALUES(124, 'loej', 'u1257', 'Cliente');
INSERT INTO usuario (idUsuario, nombreUsuario, contrasenia, rol) VALUES(125, 'lood', 'u1258', 'Cliente');
INSERT INTO usuario (idUsuario, nombreUsuario, contrasenia, rol) VALUES(126, 'mucl', 'u1259', 'Cliente');
INSERT INTO usuario (idUsuario, nombreUsuario, contrasenia, rol) VALUES(127, 'oeam', 'u1260', 'Cliente');
INSERT INTO usuario (idUsuario, nombreUsuario, contrasenia, rol) VALUES(128, 'pelc', 'u1261', 'Cliente');
INSERT INTO usuario (idUsuario, nombreUsuario, contrasenia, rol) VALUES(129, 'rivn', 'u1262', 'Cliente');
INSERT INTO usuario (idUsuario, nombreUsuario, contrasenia, rol) VALUES(130, 'rogv', 'u1263', 'Cliente');
INSERT INTO usuario (idUsuario, nombreUsuario, contrasenia, rol) VALUES(131, 'savd', 'u1264', 'Cliente');
INSERT INTO usuario (idUsuario, nombreUsuario, contrasenia, rol) VALUES(132, 'toce', 'u1265', 'Cliente');
INSERT INTO usuario (idUsuario, nombreUsuario, contrasenia, rol) VALUES(133, 'tepo', 'u1266', 'Cliente');

-- Datos de Empleados [empleado]:
-- Empleado Virtual del Administrador:
INSERT INTO empleado (idEmpleado, numeroEmpleado, puesto, estatus, foto, rutaFoto, idPersona, idUsuario) VALUES( 1, '', 'Gerente', 1, '', '', 1, 1);
--  
INSERT INTO empleado (idEmpleado, numeroEmpleado, puesto, estatus, foto, rutaFoto, idPersona, idUsuario) VALUES( 101, 'AOVP1524661310', 'Gerente', 1, '', '', 101, 101);
INSERT INTO empleado (idEmpleado, numeroEmpleado, puesto, estatus, foto, rutaFoto, idPersona, idUsuario) VALUES( 102, 'AEDL1524661310', 'Gerente', 1, '', '', 102, 102);
INSERT INTO empleado (idEmpleado, numeroEmpleado, puesto, estatus, foto, rutaFoto, idPersona, idUsuario) VALUES( 103, 'BARJ1524661310', 'Gerente', 1, '', '', 103, 103);
INSERT INTO empleado (idEmpleado, numeroEmpleado, puesto, estatus, foto, rutaFoto, idPersona, idUsuario) VALUES( 104, 'BEMM1524661310', 'Recepcionista', 1, '', '', 104, 104);
INSERT INTO empleado (idEmpleado, numeroEmpleado, puesto, estatus, foto, rutaFoto, idPersona, idUsuario) VALUES( 105, 'COAL1524661310', 'Recepcionista', 1, '', '', 105, 105);
INSERT INTO empleado (idEmpleado, numeroEmpleado, puesto, estatus, foto, rutaFoto, idPersona, idUsuario) VALUES( 106, 'FEVB1524661310', 'Recepcionista', 1, '', '', 106, 106);
INSERT INTO empleado (idEmpleado, numeroEmpleado, puesto, estatus, foto, rutaFoto, idPersona, idUsuario) VALUES( 107, 'GUMJ1524661310', 'Recepcionista', 1, '', '', 107, 107);
INSERT INTO empleado (idEmpleado, numeroEmpleado, puesto, estatus, foto, rutaFoto, idPersona, idUsuario) VALUES( 108, 'HEPA1524661310', 'Tecnico', 1, '', '', 108, 108);
INSERT INTO empleado (idEmpleado, numeroEmpleado, puesto, estatus, foto, rutaFoto, idPersona, idUsuario) VALUES( 109, 'JISE1524661310', 'Tecnico', 1, '', '', 109, 109);
INSERT INTO empleado (idEmpleado, numeroEmpleado, puesto, estatus, foto, rutaFoto, idPersona, idUsuario) VALUES( 110, 'QURL1524661310', 'Tecnico', 1, '', '', 110, 110);
INSERT INTO empleado (idEmpleado, numeroEmpleado, puesto, estatus, foto, rutaFoto, idPersona, idUsuario) VALUES( 111, 'RARJ1524661310', 'Tecnico', 1, '', '', 111, 111);
INSERT INTO empleado (idEmpleado, numeroEmpleado, puesto, estatus, foto, rutaFoto, idPersona, idUsuario) VALUES( 112, 'RIRM1524661310', 'Tecnico', 1, '', '', 112, 112);
INSERT INTO empleado (idEmpleado, numeroEmpleado, puesto, estatus, foto, rutaFoto, idPersona, idUsuario) VALUES( 113, 'SARM1524661310', 'Tecnico', 1, '', '', 113, 113);
INSERT INTO empleado (idEmpleado, numeroEmpleado, puesto, estatus, foto, rutaFoto, idPersona, idUsuario) VALUES( 114, 'SACJ1524661310', 'Tecnico', 1, '', '', 114, 114);
INSERT INTO empleado (idEmpleado, numeroEmpleado, puesto, estatus, foto, rutaFoto, idPersona, idUsuario) VALUES( 115, 'SAGJ1524661310', 'Tecnico', 1, '', '', 115, 115);
INSERT INTO empleado (idEmpleado, numeroEmpleado, puesto, estatus, foto, rutaFoto, idPersona, idUsuario) VALUES( 116, 'SAPM1524661310', 'Tecnico', 1, '', '', 116, 116);

--	Datos de Sucursales [sucursal]:
INSERT INTO sucursal (idSucursal, nombre, domicilio, longitud, latitud) VALUES(1, 'Sucursal Centro', 'Belizario Dominguez, #418, Col. Centro', -101.682636, 21.12117);
INSERT INTO sucursal (idSucursal, nombre, domicilio, longitud, latitud) VALUES(2, 'Sucursal Arbide', 'Puerto Rico #208, Col. Arbide', -101.696867, 21.123116);
INSERT INTO sucursal (idSucursal, nombre, domicilio, longitud, latitud) VALUES(3, 'Sucursal Villa Insurgentes', 'Ignacio PÃ©rez  #403, Col. Villa Insurgentes', -101.668407, 21.142708);

--      Datos de Salas [sala]:
INSERT INTO sala (idSala, nombre, descripcion, foto, rutaFoto, estatus, idSucursal) values(1, 'Nature', 'Sala que estimula los sentidos en un ambiente completamente natural, cielo de colores, espacio verde, ideal para toma de aromaterapia y masaje con esencias naturales', '', '', 1, 1);
INSERT INTO sala (idSala, nombre, descripcion, foto, rutaFoto, estatus, idSucursal) values(2, 'Harmony', 'Sala dedicada a restaurar la armonía cuerpo-mente, cielo de bosque, espacio boscoso, ideal para tratamientos de Peeling corporal suave, Batido natural a escoger y Masaje con aceites esenciales', '', '', 1, 1);
INSERT INTO sala (idSala, nombre, descripcion, foto, rutaFoto, estatus, idSucursal) values(3, 'True Rest', 'Sala que favorece el relajamiento y liberación de tensiones, cielo estrellado, espacio galaxia, ideal para la toma de todos los tipos de masajes.', '', '', 1, 1);
INSERT INTO sala (idSala, nombre, descripcion, foto, rutaFoto, estatus, idSucursal) values(4, 'Aqua', 'Sala dedicada a los amantes de ambientes marinos, cielo natural, espacio marino, ideal para tratamientos de Hidroterapia, Bañera de hidromasaje, Ducha de sensaciones, Masaje Hawaiano', '', '', 1, 1);
INSERT INTO sala (idSala, nombre, descripcion, foto, rutaFoto, estatus, idSucursal) values(5, 'Single', 'Sala que estimula la concentración, cielo natural, espacio adaptable (color a elegir), ideal para tratamientos de masajes y exfoliaciones. ', '', '', 1, 2);
INSERT INTO sala (idSala, nombre, descripcion, foto, rutaFoto, estatus, idSucursal) values(6, 'Balance', 'Sala que balancea los sentidos en un ambiente completamente natural, cielo y espacio verde, ideal para toma de aromaterapia y masaje con esencias naturales', '', '', 1, 2);
INSERT INTO sala (idSala, nombre, descripcion, foto, rutaFoto, estatus, idSucursal) values(7, 'Meditation', 'Sala dedicada a restaurar la armonía mente, cielo de bosque, espacio boscoso, ideal para tratamientos de Peeling corporal suave, Aromaterapia y Masaje con aceites esenciales', '', '', 1, 2);
INSERT INTO sala (idSala, nombre, descripcion, foto, rutaFoto, estatus, idSucursal) values(8, 'Advance', 'Sala que te hará sentir especial, cielo al natural, ambiente persa, ideal para que se pueda tomar cualquiera de los tratamientos disponibles. ', '', '', 1, 3);

--      Dastos de Productos [producto]:
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(1, 'Aceite esencial de Albahaca', 'healths', 1, 35);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(2, 'Aceite esencial de Aloe vera', 'healths', 1, 35);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(3, 'Aceite esencial de Anís', 'healths', 1, 35);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(4, 'Aceite esencial de Arbol de té', 'healths', 1, 35);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(5, 'Aceite esencial de Arnica', 'healths', 1, 35);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(6, 'Aceite esencial de Bergamota', 'healths', 1, 35);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(7, 'Aceite esencial de Caléndula', 'healths', 1, 35);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(8, 'Aceite esencial de Canela', 'healths', 1, 35);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(9, 'Aceite esencial de Cardamomo', 'healths', 1, 35);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(10, 'Aceite esencial de Cilantro', 'healths', 1, 35);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(11, 'Aceite esencial de Ciprés', 'healths', 1, 35);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(12, 'Aceite esencial de Citronela', 'healths', 1, 35);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(13, 'Aceite esencial de Clavo', 'healths', 1, 35);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(14, 'Aceite esencial de Enebro', 'healths', 1, 35);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(15, 'Aceite esencial de Eucalipto', 'healths', 1, 35);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(16, 'Aceite esencial de Gaulteria', 'healths', 1, 35);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(17, 'Aceite esencial de Geranio', 'healths', 1, 35);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(18, 'Aceite esencial de Incienso', 'healths', 1, 35);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(19, 'Aceite esencial de Jazmín', 'healths', 1, 35);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(20, 'Aceite esencial de Jengibre', 'healths', 1, 35);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(21, 'Aceite esencial de Laurel', 'healths', 1, 35);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(22, 'Aceite esencial de Lavanda', 'healths', 1, 35);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(23, 'Aceite esencial de Lima', 'healths', 1, 35);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(24, 'Aceite esencial de Limón', 'healths', 1, 35);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(25, 'Aceite esencial de Mandarina', 'healths', 1, 35);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(26, 'Aceite esencial de Manzanilla', 'healths', 1, 35);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(27, 'Aceite esencial de Menta', 'healths', 1, 35);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(28, 'Aceite esencial de Mirra', 'healths', 1, 35);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(29, 'Aceite esencial de Naranja', 'healths', 1, 35);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(30, 'Aceite esencial de Neroli', 'healths', 1, 35);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(31, 'Aceite esencial de Orégano', 'healths', 1, 35);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(32, 'Aceite esencial de Pachulí', 'healths', 1, 35);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(33, 'Aceite esencial de Palo de rosa', 'healths', 1, 35);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(34, 'Aceite esencial de Perejil', 'healths', 1, 35);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(35, 'Aceite esencial de Pino', 'healths', 1, 35);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(36, 'Aceite esencial de Pomelo', 'healths', 1, 35);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(37, 'Aceite esencial de Romero', 'healths', 1, 35);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(38, 'Aceite esencial de Rosas', 'healths', 1, 35);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(39, 'Aceite esencial de Salvia', 'healths', 1, 35);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(40, 'Aceite esencial de Sándalo', 'healths', 1, 35);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(41, 'Aceite esencial de Sésamo', 'healths', 1, 35);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(42, 'Aceite esencial de Tomillo', 'healths', 1, 35);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(43, 'Aceite esencial de Vainilla', 'healths', 1, 35);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(44, 'Aceite esencial de Vetiver', 'healths', 1, 35);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(45, 'Aceite esencial de Zanahoria', 'healths', 1, 35);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(46, 'Aceite natural de Algodón', 'healths', 1, 25);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(47, 'Aceite natural de Aloe Vera', 'healths', 1, 25);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(48, 'Aceite natural de Anís', 'healths', 1, 25);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(49, 'Aceite natural de Árbol natural de Té', 'healths', 1, 25);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(50, 'Aceite natural de Árnica', 'healths', 1, 25);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(51, 'Aceite natural de Bergamota', 'healths', 1, 25);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(52, 'Aceite natural de Borraja', 'healths', 1, 25);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(53, 'Aceite natural de Cacahuate', 'healths', 1, 25);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(54, 'Aceite natural de Caléndula', 'healths', 1, 25);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(55, 'Aceite natural de Canola', 'healths', 1, 25);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(56, 'Aceite natural de Cártamo', 'healths', 1, 25);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(57, 'Aceite natural de Citronela', 'healths', 1, 25);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(58, 'Aceite natural de Eneldo', 'healths', 1, 25);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(59, 'Aceite natural de Eucalipto', 'healths', 1, 25);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(60, 'Aceite natural de Geranio', 'healths', 1, 25);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(61, 'Aceite natural de Incienso', 'healths', 1, 25);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(62, 'Aceite natural de Jengibre', 'healths', 1, 25);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(63, 'Aceite natural de Lavanda', 'healths', 1, 25);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(64, 'Aceite natural de Limón', 'healths', 1, 25);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(65, 'Aceite natural de Maíz', 'healths', 1, 25);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(66, 'Aceite natural de Menta', 'healths', 1, 25);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(67, 'Aceite natural de Naranja', 'healths', 1, 25);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(68, 'Aceite natural de Oliva', 'healths', 1, 25);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(69, 'Aceite natural de Oregano', 'healths', 1, 25);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(70, 'Aceite natural de Palma', 'healths', 1, 25);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(71, 'Aceite natural de Pícea', 'healths', 1, 25);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(72, 'Aceite natural de Pino', 'healths', 1, 25);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(73, 'Aceite natural de Romero', 'healths', 1, 25);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(74, 'Aceite natural de Rosa Mosqueta', 'healths', 1, 25);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(75, 'Aceite natural de Sándalo', 'healths', 1, 25);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(76, 'Aceite natural de Sésamo', 'healths', 1, 25);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(77, 'Crema de Algodón', 'h&h', 1, 30);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(78, 'Crema de Aloe Vera', 'h&h', 1, 30);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(79, 'Crema de Anís', 'h&h', 1, 30);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(80, 'Crema de Árbol natural de Té', 'h&h', 1, 30);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(81, 'Crema de Árnica', 'h&h', 1, 30);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(82, 'Crema de Bergamota', 'h&h', 1, 30);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(83, 'Crema de Borraja', 'h&h', 1, 30);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(84, 'Crema de Cacahuate', 'h&h', 1, 30);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(85, 'Crema de Caléndula', 'h&h', 1, 30);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(86, 'Crema de Canola', 'h&h', 1, 30);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(87, 'Crema de Cártamo', 'h&h', 1, 30);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(88, 'Crema de Citronela', 'h&h', 1, 30);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(89, 'Crema de Eneldo', 'h&h', 1, 30);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(90, 'Crema de Eucalipto', 'h&h', 1, 30);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(91, 'Crema de Geranio', 'h&h', 1, 30);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(92, 'Crema de Incienso', 'h&h', 1, 30);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(93, 'Crema de Jengibre', 'h&h', 1, 30);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(94, 'Crema de Lavanda', 'h&h', 1, 30);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(95, 'Crema de Limón', 'h&h', 1, 30);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(96, 'Crema de Maíz', 'h&h', 1, 30);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(97, 'Crema de Menta', 'h&h', 1, 30);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(98, 'Crema de Naranja', 'h&h', 1, 30);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(99, 'Crema de Oliva', 'h&h', 1, 30);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(100, 'Crema de Oregano', 'h&h', 1, 30);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(101, 'Crema de Palma', 'h&h', 1, 30);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(102, 'Crema de Pícea', 'h&h', 1, 30);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(103, 'Crema de Pino', 'h&h', 1, 30);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(104, 'Crema de Romero', 'h&h', 1, 30);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(105, 'Crema de Rosa Mosqueta', 'h&h', 1, 30);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(106, 'Crema de Sándalo', 'h&h', 1, 30);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(107, 'Crema de Sésamo', 'h&h', 1, 30);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(108, 'Esencia de Albahaca', 'healths', 1, 15);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(109, 'Esencia de Algodón', 'healths', 1, 15);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(110, 'Esencia de Aloe vera', 'healths', 1, 15);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(111, 'Esencia de Anís', 'healths', 1, 15);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(112, 'Esencia de Árbol natural Esencia de Té', 'healths', 1, 15);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(113, 'Esencia de Árnica', 'healths', 1, 15);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(114, 'Esencia de Bergamota', 'healths', 1, 15);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(115, 'Esencia de Borraja', 'healths', 1, 15);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(116, 'Esencia de Cacahuate', 'healths', 1, 15);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(117, 'Esencia de Caléndula', 'healths', 1, 15);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(118, 'Esencia de Canela', 'healths', 1, 15);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(119, 'Esencia de Canola', 'healths', 1, 15);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(120, 'Esencia de Cardamomo', 'healths', 1, 15);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(121, 'Esencia de Cártamo', 'healths', 1, 15);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(122, 'Esencia de Cilantro', 'healths', 1, 15);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(123, 'Esencia de Ciprés', 'healths', 1, 15);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(124, 'Esencia de Citronela', 'healths', 1, 15);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(125, 'Esencia de Clavo', 'healths', 1, 15);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(126, 'Esencia de Enebro', 'healths', 1, 15);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(127, 'Esencia de Eneldo', 'healths', 1, 15);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(128, 'Esencia de Eucalipto', 'healths', 1, 15);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(129, 'Esencia de Gaulteria', 'healths', 1, 15);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(130, 'Esencia de Geranio', 'healths', 1, 15);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(131, 'Esencia de Incienso', 'healths', 1, 15);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(132, 'Esencia de Jazmín', 'healths', 1, 15);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(133, 'Esencia de Jengibre', 'healths', 1, 15);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(134, 'Esencia de Laurel', 'healths', 1, 15);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(135, 'Esencia de Lavanda', 'healths', 1, 15);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(136, 'Esencia de Lima', 'healths', 1, 15);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(137, 'Esencia de Limón', 'healths', 1, 15);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(138, 'Esencia de Maíz', 'healths', 1, 15);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(139, 'Esencia de Manzanilla', 'healths', 1, 15);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(140, 'Esencia de Menta', 'healths', 1, 15);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(141, 'Esencia de Mirra', 'healths', 1, 15);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(142, 'Esencia de Naranja', 'healths', 1, 15);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(143, 'Esencia de Neroli', 'healths', 1, 15);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(144, 'Esencia de Oliva', 'healths', 1, 15);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(145, 'Esencia de Orégano', 'healths', 1, 15);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(146, 'Esencia de Pachulí', 'healths', 1, 15);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(147, 'Esencia de Palma', 'healths', 1, 15);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(148, 'Esencia de Palo Esencia de rosa', 'healths', 1, 15);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(149, 'Esencia de Perejil', 'healths', 1, 15);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(150, 'Esencia de Pícea', 'healths', 1, 15);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(151, 'Esencia de Pino', 'healths', 1, 15);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(152, 'Esencia de Pomelo', 'healths', 1, 15);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(153, 'Esencia de Romero', 'healths', 1, 15);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(154, 'Esencia de Rosa Mosqueta', 'healths', 1, 15);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(155, 'Esencia de Rosas', 'healths', 1, 15);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(156, 'Esencia de Salvia', 'healths', 1, 15);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(157, 'Esencia de Sándalo', 'healths', 1, 15);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(158, 'Esencia de Sésamo', 'healths', 1, 15);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(159, 'Esencia de Tomillo', 'healths', 1, 15);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(160, 'Esencia de Vainilla', 'healths', 1, 15);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(161, 'Esencia de Vetiver', 'healths', 1, 15);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(162, 'Esencia de Zanahoria', 'healths', 1, 15);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(163, 'Exfoliante de Albahaca', 'healths', 1, 33);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(164, 'Exfoliante de Algodón', 'healths', 1, 33);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(165, 'Exfoliante de Aloe vera', 'healths', 1, 33);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(166, 'Exfoliante de Anís', 'healths', 1, 33);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(167, 'Exfoliante de Árbol natural Exfoliante de Té', 'healths', 1, 33);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(168, 'Exfoliante de Árnica', 'healths', 1, 33);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(169, 'Exfoliante de Bergamota', 'healths', 1, 33);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(170, 'Exfoliante de Borraja', 'healths', 1, 33);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(171, 'Exfoliante de Cacahuate', 'healths', 1, 33);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(172, 'Exfoliante de Caléndula', 'healths', 1, 33);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(173, 'Exfoliante de Canela', 'healths', 1, 33);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(174, 'Exfoliante de Canola', 'healths', 1, 33);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(175, 'Exfoliante de Cardamomo', 'healths', 1, 33);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(176, 'Exfoliante de Cártamo', 'healths', 1, 33);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(177, 'Exfoliante de Cilantro', 'healths', 1, 33);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(178, 'Exfoliante de Ciprés', 'healths', 1, 33);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(179, 'Exfoliante de Citronela', 'healths', 1, 33);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(180, 'Exfoliante de Clavo', 'healths', 1, 33);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(181, 'Exfoliante de Enebro', 'healths', 1, 33);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(182, 'Exfoliante de Eneldo', 'healths', 1, 33);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(183, 'Exfoliante de Eucalipto', 'healths', 1, 33);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(184, 'Exfoliante de Gaulteria', 'healths', 1, 33);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(185, 'Exfoliante de Geranio', 'healths', 1, 33);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(186, 'Exfoliante de Incienso', 'healths', 1, 33);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(187, 'Exfoliante de Jazmín', 'healths', 1, 33);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(188, 'Exfoliante de Jengibre', 'healths', 1, 33);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(189, 'Exfoliante de Laurel', 'healths', 1, 33);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(190, 'Exfoliante de Lavanda', 'healths', 1, 33);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(191, 'Exfoliante de Lima', 'healths', 1, 33);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(192, 'Exfoliante de Limón', 'healths', 1, 33);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(193, 'Exfoliante de Maíz', 'healths', 1, 33);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(194, 'Exfoliante de Manzanilla', 'healths', 1, 33);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(195, 'Exfoliante de Menta', 'healths', 1, 33);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(196, 'Exfoliante de Mirra', 'healths', 1, 33);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(197, 'Exfoliante de Naranja', 'healths', 1, 33);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(198, 'Exfoliante de Neroli', 'healths', 1, 33);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(199, 'Exfoliante de Oliva', 'healths', 1, 33);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(200, 'Exfoliante de Orégano', 'healths', 1, 33);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(201, 'Exfoliante de Pachulí', 'healths', 1, 33);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(202, 'Exfoliante de Palma', 'healths', 1, 33);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(203, 'Exfoliante de Palo Exfoliante de rosa', 'healths', 1, 33);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(204, 'Exfoliante de Perejil', 'healths', 1, 33);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(205, 'Exfoliante de Pícea', 'healths', 1, 33);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(206, 'Exfoliante de Pino', 'healths', 1, 33);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(207, 'Exfoliante de Pomelo', 'healths', 1, 33);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(208, 'Exfoliante de Romero', 'healths', 1, 33);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(209, 'Exfoliante de Rosa Mosqueta', 'healths', 1, 33);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(210, 'Exfoliante de Rosas', 'healths', 1, 33);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(211, 'Exfoliante de Salvia', 'healths', 1, 33);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(212, 'Exfoliante de Sándalo', 'healths', 1, 33);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(213, 'Exfoliante de Sésamo', 'healths', 1, 33);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(214, 'Exfoliante de Tomillo', 'healths', 1, 33);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(215, 'Exfoliante de Vainilla', 'healths', 1, 33);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(216, 'Exfoliante de Vetiver', 'healths', 1, 33);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(217, 'Exfoliante de Zanahoria', 'healths', 1, 33);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(218, 'Gel de de Albahaca', 'h&h', 1, 37);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(219, 'Gel de de Aloe vera', 'h&h', 1, 37);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(220, 'Gel de de Anís', 'h&h', 1, 37);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(221, 'Gel de de Arbol de té', 'h&h', 1, 37);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(222, 'Gel de de Arnica', 'h&h', 1, 37);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(223, 'Gel de de Bergamota', 'h&h', 1, 37);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(224, 'Gel de de Caléndula', 'h&h', 1, 37);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(225, 'Gel de de Canela', 'h&h', 1, 37);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(226, 'Gel de de Cardamomo', 'h&h', 1, 37);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(227, 'Gel de de Cilantro', 'h&h', 1, 37);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(228, 'Gel de de Ciprés', 'h&h', 1, 37);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(229, 'Gel de de Citronela', 'h&h', 1, 37);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(230, 'Gel de de Clavo', 'h&h', 1, 37);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(231, 'Gel de de Enebro', 'h&h', 1, 37);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(232, 'Gel de de Eucalipto', 'h&h', 1, 37);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(233, 'Gel de de Gaulteria', 'h&h', 1, 37);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(234, 'Gel de de Geranio', 'h&h', 1, 37);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(235, 'Gel de de Incienso', 'h&h', 1, 37);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(236, 'Gel de de Jazmín', 'h&h', 1, 37);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(237, 'Gel de de Jengibre', 'h&h', 1, 37);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(238, 'Gel de de Laurel', 'h&h', 1, 37);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(239, 'Gel de de Lavanda', 'h&h', 1, 37);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(240, 'Gel de de Lima', 'h&h', 1, 37);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(241, 'Gel de de Limón', 'h&h', 1, 37);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(242, 'Gel de de Mandarina', 'h&h', 1, 37);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(243, 'Gel de de Manzanilla', 'h&h', 1, 37);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(244, 'Gel de de Menta', 'h&h', 1, 37);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(245, 'Gel de de Mirra', 'h&h', 1, 37);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(246, 'Gel de de Naranja', 'h&h', 1, 37);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(247, 'Gel de de Neroli', 'h&h', 1, 37);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(248, 'Gel de de Orégano', 'h&h', 1, 37);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(249, 'Gel de de Pachulí', 'h&h', 1, 37);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(250, 'Gel de de Palo de rosa', 'h&h', 1, 37);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(251, 'Gel de de Perejil', 'h&h', 1, 37);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(252, 'Gel de de Pino', 'h&h', 1, 37);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(253, 'Gel de de Pomelo', 'h&h', 1, 37);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(254, 'Gel de de Romero', 'h&h', 1, 37);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(255, 'Gel de de Rosas', 'h&h', 1, 37);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(256, 'Gel de de Salvia', 'h&h', 1, 37);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(257, 'Gel de de Sándalo', 'h&h', 1, 37);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(258, 'Gel de de Sésamo', 'h&h', 1, 37);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(259, 'Gel de de Tomillo', 'h&h', 1, 37);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(260, 'Gel de de Vainilla', 'h&h', 1, 37);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(261, 'Gel de de Vetiver', 'h&h', 1, 37);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(262, 'Gel de de Zanahoria', 'h&h', 1, 37);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(263, 'Leche de Albahaca', 'homes', 1, 42);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(264, 'Leche de Aloe vera', 'h&h', 1, 42);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(265, 'Leche de Anís', 'h&h', 1, 42);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(266, 'Leche de Arbol de té', 'h&h', 1, 42);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(267, 'Leche de Arnica', 'h&h', 1, 42);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(268, 'Leche de Bergamota', 'h&h', 1, 42);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(269, 'Leche de Caléndula', 'h&h', 1, 42);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(270, 'Leche de Canela', 'h&h', 1, 42);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(271, 'Leche de Cardamomo', 'h&h', 1, 42);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(272, 'Leche de Cilantro', 'h&h', 1, 42);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(273, 'Leche de Ciprés', 'h&h', 1, 42);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(274, 'Leche de Citronela', 'h&h', 1, 42);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(275, 'Leche de Clavo', 'h&h', 1, 42);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(276, 'Leche de Enebro', 'h&h', 1, 42);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(277, 'Leche de Eucalipto', 'h&h', 1, 42);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(278, 'Leche de Gaulteria', 'h&h', 1, 42);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(279, 'Leche de Geranio', 'h&h', 1, 42);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(280, 'Leche de Incienso', 'h&h', 1, 42);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(281, 'Leche de Jazmín', 'h&h', 1, 42);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(282, 'Leche de Jengibre', 'h&h', 1, 42);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(283, 'Leche de Laurel', 'h&h', 1, 42);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(284, 'Leche de Lavanda', 'h&h', 1, 42);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(285, 'Leche de Lima', 'h&h', 1, 42);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(286, 'Leche de Limón', 'h&h', 1, 42);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(287, 'Leche de Mandarina', 'h&h', 1, 42);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(288, 'Leche de Manzanilla', 'h&h', 1, 42);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(289, 'Leche de Menta', 'h&h', 1, 42);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(290, 'Leche de Mirra', 'h&h', 1, 42);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(291, 'Leche de Naranja', 'h&h', 1, 42);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(292, 'Leche de Neroli', 'h&h', 1, 42);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(293, 'Leche de Orégano', 'h&h', 1, 42);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(294, 'Leche de Pachulí', 'h&h', 1, 42);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(295, 'Leche de Palo de rosa', 'h&h', 1, 42);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(296, 'Leche de Perejil', 'h&h', 1, 42);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(297, 'Leche de Pino', 'h&h', 1, 42);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(298, 'Leche de Pomelo', 'h&h', 1, 42);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(299, 'Leche de Romero', 'h&h', 1, 42);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(300, 'Leche de Rosas', 'h&h', 1, 42);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(301, 'Leche de Salvia', 'h&h', 1, 42);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(302, 'Leche de Sándalo', 'h&h', 1, 42);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(303, 'Leche de Sésamo', 'h&h', 1, 42);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(304, 'Leche de Tomillo', 'h&h', 1, 42);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(305, 'Leche de Vainilla', 'h&h', 1, 42);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(306, 'Leche de Vetiver', 'h&h', 1, 42);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(307, 'Leche de Zanahoria', 'h&h', 1, 42);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(308, 'Mermelada de Albahaca', 'h&h', 1, 38);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(309, 'Mermelada de Algodón', 'h&h', 1, 38);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(310, 'Mermelada de Aloe vera', 'h&h', 1, 38);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(311, 'Mermelada de Anís', 'h&h', 1, 38);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(312, 'Mermelada de Árbol natural Mermelada de Té', 'h&h', 1, 38);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(313, 'Mermelada de Árnica', 'h&h', 1, 38);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(314, 'Mermelada de Bergamota', 'h&h', 1, 38);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(315, 'Mermelada de Borraja', 'h&h', 1, 38);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(316, 'Mermelada de Cacahuate', 'h&h', 1, 38);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(317, 'Mermelada de Caléndula', 'h&h', 1, 38);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(318, 'Mermelada de Canela', 'h&h', 1, 38);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(319, 'Mermelada de Canola', 'h&h', 1, 38);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(320, 'Mermelada de Cardamomo', 'h&h', 1, 38);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(321, 'Mermelada de Cártamo', 'h&h', 1, 38);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(322, 'Mermelada de Cilantro', 'h&h', 1, 38);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(323, 'Mermelada de Ciprés', 'h&h', 1, 38);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(324, 'Mermelada de Citronela', 'h&h', 1, 38);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(325, 'Mermelada de Clavo', 'h&h', 1, 38);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(326, 'Mermelada de Enebro', 'h&h', 1, 38);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(327, 'Mermelada de Eneldo', 'h&h', 1, 38);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(328, 'Mermelada de Eucalipto', 'h&h', 1, 38);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(329, 'Mermelada de Gaulteria', 'h&h', 1, 38);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(330, 'Mermelada de Geranio', 'h&h', 1, 38);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(331, 'Mermelada de Incienso', 'h&h', 1, 38);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(332, 'Mermelada de Jazmín', 'h&h', 1, 38);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(333, 'Mermelada de Jengibre', 'h&h', 1, 38);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(334, 'Mermelada de Laurel', 'h&h', 1, 38);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(335, 'Mermelada de Lavanda', 'h&h', 1, 38);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(336, 'Mermelada de Lima', 'h&h', 1, 38);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(337, 'Mermelada de Limón', 'h&h', 1, 38);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(338, 'Mermelada de Maíz', 'h&h', 1, 38);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(339, 'Mermelada de Manzanilla', 'h&h', 1, 38);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(340, 'Mermelada de Menta', 'h&h', 1, 38);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(341, 'Mermelada de Mirra', 'h&h', 1, 38);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(342, 'Mermelada de Naranja', 'h&h', 1, 38);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(343, 'Mermelada de Neroli', 'h&h', 1, 38);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(344, 'Mermelada de Oliva', 'h&h', 1, 38);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(345, 'Mermelada de Orégano', 'h&h', 1, 38);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(346, 'Mermelada de Pachulí', 'h&h', 1, 38);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(347, 'Mermelada de Palma', 'h&h', 1, 38);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(348, 'Mermelada de Palo Mermelada de rosa', 'h&h', 1, 38);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(349, 'Mermelada de Perejil', 'h&h', 1, 38);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(350, 'Mermelada de Pícea', 'h&h', 1, 38);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(351, 'Mermelada de Pino', 'h&h', 1, 38);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(352, 'Mermelada de Pomelo', 'h&h', 1, 38);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(353, 'Mermelada de Romero', 'h&h', 1, 38);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(354, 'Mermelada de Rosa Mosqueta', 'h&h', 1, 38);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(355, 'Mermelada de Rosas', 'h&h', 1, 38);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(356, 'Mermelada de Salvia', 'h&h', 1, 38);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(357, 'Mermelada de Sándalo', 'h&h', 1, 38);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(358, 'Mermelada de Sésamo', 'h&h', 1, 38);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(359, 'Mermelada de Tomillo', 'h&h', 1, 38);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(360, 'Mermelada de Vainilla', 'h&h', 1, 38);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(361, 'Mermelada de Vetiver', 'h&h', 1, 38);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(362, 'Mermelada de Zanahoria', 'h&h', 1, 38);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(363, 'Peeling corporal', 'salesymas', 1, 87);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(364, 'Peeling facial', 'salesymas', 1, 44);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(365, 'Sales con Algodón', 'salesymas', 1, 46);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(366, 'Sales con Aloe Vera', 'salesymas', 1, 46);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(367, 'Sales con Anís', 'salesymas', 1, 46);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(368, 'Sales con Árbol natural de Té', 'salesymas', 1, 46);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(369, 'Sales con Árnica', 'salesymas', 1, 46);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(370, 'Sales con Bergamota', 'salesymas', 1, 46);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(371, 'Sales con Borraja', 'salesymas', 1, 46);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(372, 'Sales con Cacahuate', 'salesymas', 1, 46);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(373, 'Sales con Caléndula', 'salesymas', 1, 46);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(374, 'Sales con Canola', 'salesymas', 1, 46);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(375, 'Sales con Cártamo', 'salesymas', 1, 46);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(376, 'Sales con Citronela', 'salesymas', 1, 46);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(377, 'Sales con Eneldo', 'salesymas', 1, 46);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(378, 'Sales con Eucalipto', 'salesymas', 1, 46);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(379, 'Sales con Geranio', 'salesymas', 1, 46);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(380, 'Sales con Incienso', 'salesymas', 1, 46);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(381, 'Sales con Jengibre', 'salesymas', 1, 46);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(382, 'Sales con Lavanda', 'salesymas', 1, 46);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(383, 'Sales con Limón', 'salesymas', 1, 46);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(384, 'Sales con Maíz', 'salesymas', 1, 46);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(385, 'Sales con Menta', 'salesymas', 1, 46);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(386, 'Sales con Naranja', 'salesymas', 1, 46);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(387, 'Sales con Oliva', 'salesymas', 1, 46);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(388, 'Sales con Oregano', 'salesymas', 1, 46);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(389, 'Sales con Palma', 'salesymas', 1, 46);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(390, 'Sales con Pícea', 'salesymas', 1, 46);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(391, 'Sales con Pino', 'salesymas', 1, 46);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(392, 'Sales con Romero', 'salesymas', 1, 46);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(393, 'Sales con Rosa Mosqueta', 'salesymas', 1, 46);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(394, 'Sales con Sándalo', 'salesymas', 1, 46);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(395, 'Sales con Sésamo', 'salesymas', 1, 46);
INSERT INTO producto (idProducto, nombre, marca, estatus, precioUso) VALUES(396, 'Vela de té', 'salesymas', 1, 5);


--      Datos de tratamientos [tratamiento]:
INSERT INTO tratamiento (idTratamiento, nombre, descripcion, costo) VALUES (1, 'Aromaterapia', 'Descansa y relájate en un ambiente especial, mientras inhalas esencias naturales que te ayudaran a mejorar tu estado emocional. ', 315);
INSERT INTO tratamiento (idTratamiento, nombre, descripcion, costo) VALUES (2, 'Batido natural', 'La leche tiene propiedades que producen colágeno, que reafirman y hacen que la piel sea más flexible. Este tratamiento consiste en un masaje general (facial y corporal) basado en cremas y leches naturales.', 320);
INSERT INTO tratamiento (idTratamiento, nombre, descripcion, costo) VALUES (3, 'Ducha de sensaciones', 'Es un masaje energético que combina masaje corporal, facial, del cuero cabelludo, siempre al ritmo de la música, con uso de esencias de aromaterapia finalizando con hidromasaje.', 252);
INSERT INTO tratamiento (idTratamiento, nombre, descripcion, costo) VALUES (4, 'Exfoliación corporal', 'Es un tratamiento específico para la eliminación de las células muertas de la piel mediante el uso de exfoliantes y emolientes naturales.', 301);
INSERT INTO tratamiento (idTratamiento, nombre, descripcion, costo) VALUES (5, 'Exfoliación facial', 'Es un tratamiento específico para la eliminación de las células muertas de la piel facial mediante el uso de exfoliantes y emolientes naturales.', 213);
INSERT INTO tratamiento (idTratamiento, nombre, descripcion, costo) VALUES (6, 'Hidromasaje', 'El tratamientos de hidromasaje esta concebido para ofrecer la relajación y el placer del agua sobre todo el cuerpo junto con los beneficios de la cromoterapia.', 159);
INSERT INTO tratamiento (idTratamiento, nombre, descripcion, costo) VALUES (7, 'Hidroterapia', 'El tratamientos de hidroterapia esta concebido para ofrecer la relajación y el placer del agua sobre todo el cuerpo, primero se proporciona un masaje corporal, para después pasar a la tina de hidromasaje junto con los beneficios de la cromoterapia, y aromaterapia.', 362);
INSERT INTO tratamiento (idTratamiento, nombre, descripcion, costo) VALUES (8, 'Masaje con aceites esenciales', 'Disfruta de un rato inolvidable con el masaje de aceites esenciales, podrás elegir los aceites a tu gusto con los que recibirás un delicado y relajante masaje general (facial y corporal).', 184);
INSERT INTO tratamiento (idTratamiento, nombre, descripcion, costo) VALUES (9, 'Masaje con esencias naturales', 'Disfruta de un rato inolvidable con la micro exfoliación y el masaje de esencias naturales podrás elegir los componentes a tu gusto con los que recibirás un delicado y relajante masaje general (facial y corporal).', 241);
INSERT INTO tratamiento (idTratamiento, nombre, descripcion, costo) VALUES (10, 'Masaje Hawaiano', 'Masaje terapéutico acompañado de la aplicación de frutos naturales como base del masaje.', 194);
INSERT INTO tratamiento (idTratamiento, nombre, descripcion, costo) VALUES (11, 'Peeling corporal intenso', 'El peeling corporal es un tratamiento específico para la eliminación de las células muertas de la piel con una sesión de exfoliación, seguida por el peeling , aportando frescura, suavidad y limpieza a la piel.', 298);
INSERT INTO tratamiento (idTratamiento, nombre, descripcion, costo) VALUES (12, 'Peeling corporal suave', 'El peeling facial es un tratamiento específico para la eliminación de las células muertas de la piel aportando frescura, suavidad y limpieza a la piel.', 265);
INSERT INTO tratamiento (idTratamiento, nombre, descripcion, costo) VALUES (13, 'Especial', 'Solicita libremente la combinación de tratamientos que necesites, de manera personalizada.', 318);

--      Datos de horarios [horario]
INSERT INTO horario (idHorario, horaInicio, horaFin) VALUES(1, '09:00:00', '09:30:00');
INSERT INTO horario (idHorario, horaInicio, horaFin) VALUES(2, '09:30:00', '10:00:00');
INSERT INTO horario (idHorario, horaInicio, horaFin) VALUES(3, '10:00:00', '10:30:00');
INSERT INTO horario (idHorario, horaInicio, horaFin) VALUES(4, '10:30:00', '11:00:00');
INSERT INTO horario (idHorario, horaInicio, horaFin) VALUES(5, '11:00:00', '11:30:00');
INSERT INTO horario (idHorario, horaInicio, horaFin) VALUES(6, '11:30:00', '12:00:00');
INSERT INTO horario (idHorario, horaInicio, horaFin) VALUES(7, '12:00:00', '12:30:00');
INSERT INTO horario (idHorario, horaInicio, horaFin) VALUES(8, '12:30:00', '13:00:00');
INSERT INTO horario (idHorario, horaInicio, horaFin) VALUES(9, '13:00:00', '13:30:00');
INSERT INTO horario (idHorario, horaInicio, horaFin) VALUES(10, '13:30:00', '14:00:00');

--	Datos de Clientes [cliente]:
INSERT INTO cliente (idCliente, numeroUnico, correo, estatus, idPersona, idUsuario) VALUES (1, 'AOVP43101', '', 1, 117, 117);
INSERT INTO cliente (idCliente, numeroUnico, correo, estatus, idPersona, idUsuario) VALUES (2, 'AEDL43102', '', 1, 118, 118);
INSERT INTO cliente (idCliente, numeroUnico, correo, estatus, idPersona, idUsuario) VALUES (3, 'BARJ43103', '', 1, 119, 119);
INSERT INTO cliente (idCliente, numeroUnico, correo, estatus, idPersona, idUsuario) VALUES (4, 'BEMM43104', '', 1, 120, 120);
INSERT INTO cliente (idCliente, numeroUnico, correo, estatus, idPersona, idUsuario) VALUES (5, 'COAL43105', '', 1, 121, 121);
INSERT INTO cliente (idCliente, numeroUnico, correo, estatus, idPersona, idUsuario) VALUES (6, 'FEVB43106', '', 1, 122, 122);
INSERT INTO cliente (idCliente, numeroUnico, correo, estatus, idPersona, idUsuario) VALUES (7, 'GUMJ43107', '', 1, 123, 123);
INSERT INTO cliente (idCliente, numeroUnico, correo, estatus, idPersona, idUsuario) VALUES (8, 'HEPA43108', '', 1, 124, 124);
INSERT INTO cliente (idCliente, numeroUnico, correo, estatus, idPersona, idUsuario) VALUES (9, 'JISE43109', '', 1, 125, 125);
INSERT INTO cliente (idCliente, numeroUnico, correo, estatus, idPersona, idUsuario) VALUES (10, 'QURL43110', '', 1, 126, 126);
INSERT INTO cliente (idCliente, numeroUnico, correo, estatus, idPersona, idUsuario) VALUES (11, 'RARJ43111', '', 1, 127, 127);
INSERT INTO cliente (idCliente, numeroUnico, correo, estatus, idPersona, idUsuario) VALUES (12, 'RIRM43112', '', 1, 128, 128);
INSERT INTO cliente (idCliente, numeroUnico, correo, estatus, idPersona, idUsuario) VALUES (13, 'SARM43113', '', 1, 129, 129);
INSERT INTO cliente (idCliente, numeroUnico, correo, estatus, idPersona, idUsuario) VALUES (14, 'SACJ43114', '', 1, 130, 130);
INSERT INTO cliente (idCliente, numeroUnico, correo, estatus, idPersona, idUsuario) VALUES (15, 'SAGJ43115', '', 1, 131, 131);
INSERT INTO cliente (idCliente, numeroUnico, correo, estatus, idPersona, idUsuario) VALUES (16, 'SAPM43116', '', 1, 132, 132);
INSERT INTO cliente (idCliente, numeroUnico, correo, estatus, idPersona, idUsuario) VALUES (17, 'TECB43117', '', 1, 133, 133);